const menu = [
  {
    id: 1,
    title: "spaghetti alla carbonara",
    category: "primi piatti",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. A sapiente nesciunt sunt at? Eaque, dolor.",
  },
  {
    id: 2,
    title: "pollo francese",
    category: "secondi piatti",
    price: 8.99,
    img: "./images/item-1.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione quisquam asperiores sapiente? Culpa exercitationem consequuntur.",
  },
  {
    id: 3,
    title: "profiteroles",
    category: "dolce",
    price: 10.99,
    img: "./images/item-2.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem ut enim blanditiis placeat natus repellat.",
  },

  {
    id: 4,
    title: "pollo alla parmigiana",
    category: "secondi piatti",
    price: 11.99,
    img: "./images/item-4.jpeg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque voluptatibus temporibus ex incidunt? Possimus.",
  },
  {
    id: 5,
    title: "risotto ai funghi",
    category: "primi piatti",
    price: 11.99,
    img: "./images/item-5.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptate, veritatis. Soluta voluptatibus natus id asperiores.",
  },
  {
    id: 6,
    title: "spaghetti marinara",
    category: "primi piatti",
    price: 9.99,
    img: "./images/item-6.jpeg",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Atque nesciunt delectus possimus molestiae est adipisci!",
  },
  {
    id: 7,
    title: "tiramisu",
    category: "dolce",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ab tempore praesentium, beatae eos sed!",
  },
  {
    id: 8,
    title: "tartufo",
    category: "dolce",
    price: 9.99,
    img: "./images/item-8.jpeg",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolor doloribus, assumenda asperiores voluptatibus dolores sunt!",
  },
  {
    id: 9,
    title: "fettuccine alfredo",
    category: "primi piatti",
    price: 9.99,
    img: "./images/item-9.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam laborum dicta aliquam neque adipisci harum?",
  },
  {
    id: 10,
    title: "vitello marsala",
    category: "secondi piatti",
    price: 26.99,
    img: "./images/item-10.jpeg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore nisi sequi assumenda, hic officiis eligendi?",
  },
];
export default menu;
